---
title: "Spatial Interpolation"
author: "Gan Yao"
date: "`r Sys.Date()`"
output: pdf_document
---

# Load data and preprocesssing

```{r}
library(tidyverse)
library(interp)
```

```{r}
data <- read.csv('Downhole_BedrockPicks_2023-01-06.csv')
data_2 <- data[data$BR_CLASS_TYPE==2, ]
data_2 <- data_2[!is.na(data_2$LONGITUDE),]
data_2 <- data_2[!is.na(data_2$BEDROCK_ELEV_M),]
```

```{r}
same_points = paste(data_2$LONGITUDE, data_2$LATITUDE)
```


```{r}
res <- interp(x=data_2$LONGITUDE, y=data_2$LONGITUDE, z=data_2$BEDROCK_ELEV_M, duplicate = 'strip')
```

```{r}
data_2[same_points=="-87.663581 38.727998",]
data_2[same_points==same_points[duplicated(same_points)][1],]

sum(is.element(same_points, unique(same_points[duplicated(same_points)])))
```

```{r}
red_data <- data_2 %>% group_by(LATITUDE, LONGITUDE) %>% summarise(MED = median(BEDROCK_ELEV_M), .groups = "keep")
```

```{r}
res <- interp(x=100000*red_data$LATITUDE, y=100000*red_data$LONGITUDE, z=red_data$MED, duplicate='strip')
```

```{r}
interpp(x=10000*(data_2$LATITUDE-41), y=10000*(data_2$LONGITUDE+89), z=data_2$BEDROCK_ELEV_M, xo = 10000*(data_2$LATITUDE-41),  yo = 10000*(data_2$LONGITUDE+89), duplicate='median')
```








